# Generated by Django 3.2.6 on 2024-08-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], default='PATIENT', max_length=10),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
