# Generated by Django 3.2.6 on 2024-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('MANAGER', 'manager')], default='PATIENT', max_length=10),
        ),
    ]
