# Generated by Django 3.2.6 on 2024-08-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
