# Generated by Django 3.2.6 on 2024-08-28 08:18
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20240828_0048'),
        ('home', '0011_auto_20240828_0113'),
    ]

    operations = [
         migrations.AddField(
            model_name='adddoctor',
            name='user',
           field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]