# Generated by Django 3.2.6 on 2024-08-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_merge_0010_auto_20240828_0048_0011_auto_20240828_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='AddDoctor',
        ),
    ]
