# Generated by Django 3.2.6 on 2024-08-29 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_adddoctor123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attend',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='attend',
            name='last_name',
        ),
        migrations.AddField(
            model_name='attend',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attend',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
