# Generated by Django 3.2.6 on 2024-08-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20240829_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddoctor123',
            old_name='description',
            new_name='specialist',
        ),
    ]
