from django.urls import path
from .views import (
    index,
    index1,
    index2,
    index3,
    pages,
    
    doctor_list,
    add_doctor,
    delete_doctor,
    manager_dashboard,
    doctor_dashboard,
    patient_dashboard,
    logout1,
 
    create_appointment,
    doctor_details,
    attend_create,
    attend_list,
    attend_list_m,
    dashboard,
    Appointment_details,
    Appointment_details_p,
    delete_appointment,
    about,
    AppointmentListView,
     index1View,
    index3View,
     index2View,
     AppointmentDeleteView,
     appointments_details,
  register_doctor, register_patient, login2,
  delete_appointment,
  register_manager,
  profile,
  update_appointment,


  delete_attend,
  patient_doctor_appointment,
  patient_appointments,
appointment_delete,
    appointment_update,
    update_attend, 
    delete_attend1,
    update_attend1,
    notifications_data,
      profile_p,
      profile_d ,
)

urlpatterns = [
    path('', index, name='index'),
    path('attends/update/<int:id>/', update_attend, name='update_attend'),
    path('attend/delete/<int:pk>/', delete_attend, name='delete_attend'),
    path('appointment/<int:pk>/update/', appointment_update, name='appointment_update'),
    path('appointment/<int:pk>/delete/', appointment_delete, name='appointment_delete'),
    path('appointment/<int:pk>/', patient_doctor_appointment, name='patient_doctor_appointment'),
    path('patient_appointments/', patient_appointments, name='patient_appointments'),
    path('attend/update/<int:pk>/', update_attend1, name='update_attend1'),
    path('attend/delete/<int:pk>/', delete_attend1, name='delete_attend1'),
    path('appointments/delete/<int:pk>/', delete_appointment, name='delete_appointment'),
    path('appointments/update/<int:pk>/', update_appointment, name='update_appointment'),
    path('appointments/delete/<int:appointment_id>/', delete_appointment, name='delete_appointment'),
    path('doctors/delete/<int:doctor_id>/', delete_doctor, name='delete_doctor'),
    path('login2/', login2, name='login2'),
    path('profile/', profile, name='profile'),
    path('register_manager/', register_manager, name='register_manager'),
    path('appointments/<int:appointment_id>/', Appointment_details, name='Appointment_detail'),
    path('register_doctor/', register_doctor, name='register_doctor'),
    path('register_patient/', register_patient, name='register_patient'),
    path('appointments_details/<int:appointment_id>/', appointments_details, name='appointments_details'),
    path('Appointment_details_p/', Appointment_details_p, name='Appointment_details_p'),
    path('index1/', index1View.as_view(), name='index1'),
    path('index3/', index3View.as_view(), name='index3'),
    path('index2/', index2View.as_view(), name='index2'),
    path('pages/<str:template>/', pages, name='pages'),
    path('appointments_lists/', AppointmentListView.as_view(), name='appointments_lists'),
    path('appointment_lists/', AppointmentListView.as_view(), name='appointment_lists'),
    path('doctor_list/', doctor_list, name='doctor_list'),
    path('add_doctor/', add_doctor, name='add_doctor'),
    path('doctors/delete/<int:doctor_id>/', delete_doctor, name='delete_doctor'),
    path('manager/dashboard/', manager_dashboard, name='manager_dashboard'),
    path('doctor/dashboard/', doctor_dashboard, name='doctor_dashboard'),
    path('patient/dashboard/', patient_dashboard, name='patient_dashboard'),
    path('logout1/', logout1, name='logout1'),
    
  
    path('create_appointment/', create_appointment, name='create_appointment'),
    path('doctor_details/', doctor_details, name='doctor_details'),
    path('attend_create/', attend_create, name='attend_create'),
    path('attend_list/', attend_list, name='attend_list'),
    path('attend_list_m/', attend_list_m, name='attend_list_m'),
    path('dashboard/', dashboard, name='dashboard'),
    path('Appointment_details/', Appointment_details, name='Appointment_details'),
    
    path('add_doctor/', add_doctor, name='add_doctor'),
    path('index1/', index1, name='index1'),
    path('index2/', index2, name='index2'),
    path('index3/', index3, name='index3'),
   
    path('about/', about, name='about'), 
   
       path('notifications_data/', notifications_data, name='notifications_data'),
    path('profile_p/', profile_p, name='profile_p'),
    path('profile_d/',profile_d , name='profile_d'),
     
]
